using System;
using Content.Client.Stylesheets;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes; // Carpmosia-edit - Better map vote
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VotePopup : Control
    {
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IVoteManager _voteManager = default!;
        [Dependency] private IEntityNetworkManager _net = default!;

        private readonly VoteManager.ActiveVote _vote;
        private readonly VoteOption[] _voteOptions; // Carpmosia-edit - Better map vote
        private readonly NetEntity? _targetEntity;

        public VotePopup(VoteManager.ActiveVote vote)
        {
            _vote = vote;
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSystem;

            if (_vote.TargetEntity != null && _vote.TargetEntity != 0)
            {
                _targetEntity = new NetEntity(_vote.TargetEntity.Value);
                FollowVoteTarget.Visible = true;
                FollowVoteTarget.OnPressed += _ => AttemptFollowVoteEntity();
            }

            Modulate = Color.White.WithAlpha(0.75f);
            _voteOptions = new VoteOption[vote.Entries.Length]; // Carpmosia-edit - Better map vote
            var group = new ButtonGroup();

            // Carpmosia-start - Better map vote
            for (var i = 0; i < _voteOptions.Length; i++)
            {
                var option = new VoteOption();
                option.Button.ToggleMode = true;
                option.Button.Group = group;
                _voteOptions[i] = option;
                VoteOptionsContainer.AddChild(option);
                var i1 = i;
                option.Button.OnPressed += _ => _voteManager.SendCastVote(vote.Id, i1);
            }
            // Carpmosia-end - Better map vote
        }

        public void UpdateData()
        {
            VoteTitle.SetMessage(FormattedMessage.FromUnformatted(_vote.Title));
            VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", _vote.Initiator));

            for (var i = 0; i < _voteOptions.Length; i++) // Carpmosia-edit - Better map vote
            {
                var entry = _vote.Entries[i];
                // Carpmosia-start - Better map vote
                if (entry.Icon is not null)
                {
                    _voteOptions[i].Button.IconL.TexturePath = entry.Icon;
                    _voteOptions[i].Button.IconR.TexturePath = entry.Icon;
                }
                if (entry.Preview is not null)
                {
                    _voteOptions[i].Preview.SetPrototype(entry.Preview.Value);
                }
                // Carpmosia-end - Better map vote
                if (_vote.DisplayVotes)
                {
                    _voteOptions[i].Button.IconLabel.Text = Loc.GetString("ui-vote-button", ("text", entry.Text), ("votes", entry.Votes)); // Carpmosia-edit - Better map vote
                }
                else
                {
                    _voteOptions[i].Button.IconLabel.Text = Loc.GetString("ui-vote-button-no-votes", ("text", entry.Text)); // Carpmosia-edit - Better map vote
                }

                if (_vote.OurVote == i)
                    _voteOptions[i].Button.Pressed = true; // Carpmosia-edit - Better map vote
            }
        }

        private void AttemptFollowVoteEntity()
        {
            if (_targetEntity != null)
            {
                var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
                _net.SendSystemNetworkMessage(msg);
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            // Logger.Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

            var curTime = _gameTiming.RealTime;
            var timeLeft = _vote.EndTime - curTime;
            if (timeLeft < TimeSpan.Zero)
                timeLeft = TimeSpan.Zero;

            // Round up a second.
            timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

            TimeLeftBar.Value = Math.Min(1, (float) ((curTime.TotalSeconds - _vote.StartTime.TotalSeconds) /
                                                     (_vote.EndTime.TotalSeconds - _vote.StartTime.TotalSeconds)));

            TimeLeftText.Text = $"{timeLeft:m\\:ss}";
        }
    }
}
