using Content.Shared.CCVar; // Carpmosia-edit - Better flavor text
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.Configuration;  // Carpmosia-edit - Better flavor text

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        [Dependency] private IConfigurationManager _configurationManager = default!; // Carpmosia-edit - Better flavor text

        public Action<string>? OnFlavorTextChanged;

        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var maxChars = _configurationManager.GetCVar(CCVars.MaxFlavorTextLength); // Carpmosia-edit - Better flavor text
            var loc = IoCManager.Resolve<ILocalizationManager>();
            CFlavorTextInput.PlaceHolder = loc.GetString("flavor-text-placeholder", ("maxchars", maxChars)); // Carpmosia-edit - Better flavor text
            CFlavorTextInput.OnTextChanged  += _ => FlavorTextChanged();
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(CFlavorTextInput.Text.Trim());  // Carpmosia-edit - Better flavor text
        }
    }
}
