- type: antag
  id: BloodBound
  name: roles-antag-blood-bound-name
  playTimeTracker: AntagBloodBound
  color: '#c71585'
  antagonist: true
  setPreference: true
  objective: roles-antag-blood-bound-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
  guides: [ BloodBound ]

# not actually given out, only used to check the preference
- type: antag
  id: BloodBoundConvertible
  name: roles-antag-blood-bound-convertible-name
  color: '#c71585'
  setPreference: true
  objective: roles-antag-blood-bound-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
  guides: [ BloodBound ]

- type: antagSpecifier
  parent: RestrictedAntag
  id: BloodBound
  prefRoles:
  - BloodBound
  blacklist:
    components:
    - AntagImmune
  components:
  - type: BloodBound
  - type: InitialBloodBound
  - type: IntrinsicRadioReceiver
  - type: IntrinsicRadioTransmitter
    channels:
    - BBTelepathy
  - type: ActiveRadio
    channels:
    - BBTelepathy
  mindRoles:
  - MindRoleBloodBound
  briefing:
    text: blood-bound-initial-role-greeting
    color: MediumVioletRed
    sound: "/Audio/_Carpmosia/Misc/blood_bound_greeting.ogg"

- type: antagSpecifier
  parent: RestrictedAntag
  id: BloodBoundConvertible
  prefRoles:
  - BloodBoundConvertible
  blacklist:
    components:
    - AntagImmune
  components:
  - type: BloodBound
  - type: IntrinsicRadioReceiver
  - type: IntrinsicRadioTransmitter
    channels:
    - BBTelepathy
  - type: ActiveRadio
    channels:
    - BBTelepathy
  mindRoles:
  - MindRoleBloodBound
  briefing:
    text: blood-bound-role-greeting
    color: MediumVioletRed
    sound: "/Audio/_Carpmosia/Misc/blood_bound_greeting.ogg"
